### ISSUE TITLE
Add type information for mypy support

### ISSUE THREAD

**Issue by nth10sd** [beeware/travertino#28]
**Is your feature request related to a problem? Please describe.**
Python 3.6 is now EOL, so with the minimum supported Python version at 3.7, we can possibly use `from __future__ import annotations` and start adding type hints for `mypy` support.

**Describe the solution you'd like**
Add type information.

**Describe alternatives you've considered**
There is currently no type information.

**Additional context**
None.

**Comment by freakboy3742** [comment]
Type annotations have been legal syntax since Python 3.0, so the 3.6 lifespan isn't a consideration.

Regardless, type information isn't an inherent and universal good. It *can* be helpful as an enhancement to documentation, but it can also impede readability in some circumstances.

There is a broader conversation that needs to be had here, in the context of the entire project.

I'm closing this for now, on the basis that having the ticket open won't progress this feature at all. If you want to advocate for adding annotations, I suggest starting a discussion on the BeeWare Discord.

**Comment by nth10sd** [comment]
I had fixed about 75% of the type issues present in Travertino (318 out of 1271 remaining) [on a branch](https://github.com/nth10sd/travertino/commits/add-type-hints) - however, it was done with the black code formatter PR #29 that was closed along with this, before I read your replies and reasonings for the closures of these issues/PRs.

As such, I will leave this here and stop my current contributions for trying to improve the Beeware projects in this way. @freakboy3742 I'm really sorry this was not done through the desired process.

While I feel that the advantages outweigh the disadvantages of having type hints, either in its inline or stubs form (to me, the ship has sailed, other projects are moving in that direction), I unfortunately have no desire right now to take on the "broader conversation" on whether type hints is or isn't an inherent and universal good, or its "impediment of readability".

If someone is interested in pushing this through, please feel free to use the branch as a starting point to add inline type hints.
